services:
  - type: web
    name: discord-ml-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python "Discord Bot.py"
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHON_VERSION
        value: 3.10.14
    healthCheckPath: /health
    autoDeploy: true