name: Keep Alive ping

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL on Website
        run: curl -s https://transformi.onrender.com
